### ISSUE TITLE
Is it possible to use with canvas instead of webgl?

### ISSUE THREAD

**Issue by bryandandan** [Yomguithereal/sigma-experiments#2]
I would like to use this tool with renderer canvas. How can i achieve that?

**Comment by Yomguithereal** [comment]
Hello @bryandandan. This tool has been designed for sigma v2 and sigma v2 does not have a plain canvas renderer yet, sorry.

**Comment by bryandandan** [comment]
Hello @Yomguithereal , I understand. I will try to write my own using urs as reference. Thanks!
