### ISSUE TITLE
How difficult is it to re-write this plugin for sigma v1.2.1?

### ISSUE THREAD

**Issue by bryandandan** [Yomguithereal/sigma-experiments#3]
I would like to implement the same for 1.2.1. Is there any limitation or reason it shouldn't work? How easy would it be for me to adapt it?

Thanks

**Comment by Yomguithereal** [comment]
@bryandandan it should not be too difficult. The tricky part is just to adapt the code related to coordinate translation from container to graph space.

**Comment by bryandandan** [comment]
Noted! Many thanks
